/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.Destino;
import Modelo.PaqueteTuristico;
import Modelo.PaqueteTuristicoMultiple;
import Modelo.PaqueteTuristicoUnico;
import Modelo.Venta;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class UsaGUIVenta extends javax.swing.JFrame {

    /**
     * Creates new form UsaGUIVenta
     */
    public UsaGUIVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<Venta> datosVentas;
    ArrayList<Cliente> datosClientes;
    
    public static int generarNumeroVenta(ArrayList<Venta> datosVentas){
        if(datosVentas.isEmpty()){
            return 1;
        } else {
            int maxNumero = 0;
            for(Venta v : datosVentas){
                if(v.getNumero() > maxNumero){
                    maxNumero = v.getNumero();
                }
            }
            return maxNumero + 1;
        }
    }
    
    public ArrayList<Venta> crearNuevaVenta(ArrayList<Venta> datosVentas){
        //Venta
        int numero = generarNumeroVenta(datosVentas);
        LocalDateTime fechaHoraGeneracion = LocalDateTime.now(); 
        LocalDateTime fechaHoraActualizacion = LocalDateTime.now(); 
        Cliente suCliente;
        
        //Datos del Cliente
        
        char tipoID = JOptionPane.showInputDialog("Tipo identificación (C: Cédula, N: Nit)").charAt(0);
        String numID = JOptionPane.showInputDialog("Número de identificación:");
        int esEmpresaInt = JOptionPane.showConfirmDialog(null, "¿Es una empresa?", "Tipo cliente", JOptionPane.YES_NO_OPTION); 
        boolean esEmpresa = (esEmpresaInt == JOptionPane.YES_OPTION);
        String nombre = JOptionPane.showInputDialog(esEmpresa ? "Razón social:" : "Nombre completo:");
        String email = JOptionPane.showInputDialog("Email:");
        String telefono = JOptionPane.showInputDialog("Teléfono:");
        String nombreContacto = JOptionPane.showInputDialog("Nombre de contacto:");
        double descuento = Double.parseDouble(JOptionPane.showInputDialog("Porcentaje de descuento (0-70):"));
        
        suCliente = new Cliente (tipoID, numID, esEmpresa, nombre, email, telefono, nombreContacto, descuento);
        
        //Paquetes turisticos
        
        ArrayList<PaqueteTuristico> susPaquetesTuristicos = new ArrayList<>();
        int cantidadPaquetes = Integer.parseInt(JOptionPane.showInputDialog("¿Cuántos paquetes incluye esta venta?"));
        
        for(int i=0; i<cantidadPaquetes; i++){
                JOptionPane.showMessageDialog(null, "--- DATOS DEL PAQUETE " + (i+1) + " ---");
                
                String categoria = JOptionPane.showInputDialog("Categoría (U: Único, M: Múltiple)").toUpperCase();
                String codigo = JOptionPane.showInputDialog("Código del paquete:");
                String nombrePaq = JOptionPane.showInputDialog("Nombre del paquete (mínimo 10 caracteres):");
                String tipologia = JOptionPane.showInputDialog("Tipología (negocios, recreación, educativo, ecológico):");
                String descripcion = JOptionPane.showInputDialog("Descripción:");
                String origen = JOptionPane.showInputDialog("Origen (lugar de partida):");
                
                // Destinos
                ArrayList<Destino> susDestinos = new ArrayList<>();
                int numDestinos = Integer.parseInt(JOptionPane.showInputDialog("¿Cuántos destinos incluye?"));
                for(int j=0; j<numDestinos; j++){
                    String lugar = JOptionPane.showInputDialog("Nombre del destino " + (j+1) + ":");
                    int dias = Integer.parseInt(JOptionPane.showInputDialog("Días de permanencia:"));
                    int atractivosInt = JOptionPane.showConfirmDialog(null, "¿Incluye atractivos turísticos?", "Atractivos", JOptionPane.YES_NO_OPTION);
                    boolean atractivos = (atractivosInt == JOptionPane.YES_OPTION);
                    susDestinos.add(new Destino(lugar, dias, atractivos));
                }
                
                int hotelInt = JOptionPane.showConfirmDialog(null, "¿Incluye hotel?", "Hotel", JOptionPane.YES_NO_OPTION);
                boolean hotel = (hotelInt == JOptionPane.YES_OPTION);
                int alimentacionInt = JOptionPane.showConfirmDialog(null, "¿Incluye alimentación?", "Alimentación", JOptionPane.YES_NO_OPTION);
                boolean alimentacion = (alimentacionInt == JOptionPane.YES_OPTION);
                boolean alimentacionTodo = false;
                if(alimentacion){
                    int alimentacionTodoInt = JOptionPane.showConfirmDialog(null, "¿Alimentación todo incluido?", "Tipo alimentación", JOptionPane.YES_NO_OPTION);
                    alimentacionTodo = (alimentacionTodoInt == JOptionPane.YES_OPTION);
                }
                int vueloInt = JOptionPane.showConfirmDialog(null, "¿Incluye vuelo?", "Vuelo", JOptionPane.YES_NO_OPTION);
                boolean vuelo = (vueloInt == JOptionPane.YES_OPTION);
                int asistenciaInt = JOptionPane.showConfirmDialog(null, "¿Incluye asistencia?", "Asistencia", JOptionPane.YES_NO_OPTION);
                boolean asistencia = (asistenciaInt == JOptionPane.YES_OPTION);
                int tarifaDia = Integer.parseInt(JOptionPane.showInputDialog("Tarifa por día:"));
                int cantidadUnidades = Integer.parseInt(JOptionPane.showInputDialog("Cantidad de unidades:"));
                
                if(categoria.equals("U")){
                    String nombreHotel = JOptionPane.showInputDialog("Nombre del hotel:");
                    String tipoDesayuno = null;
                    if(alimentacion){
                        tipoDesayuno = JOptionPane.showInputDialog("Tipo de desayuno (Buffet, Americano, etc.):");
                    }
                    PaqueteTuristicoUnico objPaqueteUnico = new PaqueteTuristicoUnico(nombreHotel, tipoDesayuno, codigo, nombrePaq, tipologia, descripcion, 
                            origen, susDestinos, hotel, alimentacion, alimentacionTodo, vuelo, asistencia, 
                            tarifaDia, cantidadUnidades);
                    susPaquetesTuristicos.add(objPaqueteUnico);
                } else {
                    String obsequio = JOptionPane.showInputDialog("Obsequio del paquete:");
                    PaqueteTuristicoMultiple objPaqueteMultiple = new PaqueteTuristicoMultiple(obsequio, codigo, nombrePaq, tipologia, descripcion,
                            origen, susDestinos, hotel, alimentacion, alimentacionTodo, vuelo, asistencia,
                            tarifaDia, cantidadUnidades);
                    susPaquetesTuristicos.add(objPaqueteMultiple);
                }
            }
        
        char estado; 
        
        Venta objVenta = new Venta(numero, fechaHoraGeneracion, fechaHoraActualizacion, suCliente, susPaquetesTuristicos, estado);
        
        datosVentas.add(objVenta);
        return datosVentas;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsaGUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsaGUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsaGUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsaGUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsaGUIVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
